version: '3.5'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
     - shinyproxy
     - certbot
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sp-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - sp-net
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  shinyproxy:
    image: YOUR_USERNAME/shinyproxy-example
    depends_on:
      - euler
    container_name: shinyproxy
    expose:
      - 8080
    volumes:
      - ./application/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sp-net
  euler:
    image: YOUR_USERNAME/shiny-euler-app

networks:
  sp-net:
    name: sp-net
    